container:
    image: python:3.5-slim

site_generation_task:
    only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_BRANCH == 'master' && $CIRRUS_TAG == '' && $CIRRUS_PR == '' && $CIRRUS_REPO_FULL_NAME == 'ungoogled-software/ungoogled-chromium-binaries'
    environment:
        GITHUB_PUSH_TOKEN: ENCRYPTED[TODO]
    pip_cache:
        folder: ~/.cache/pip
        populate_script: pip install Markdown
    pip_install_script: pip install Markdown
    site_generator_script:
        - git diff --cached --exit-code
        - git diff --exit-code
        - python3 utilities/site_generator.py
        - ! git diff --exit-code || exit
        - git add *
        - git config user.email 'cirrus@null'
        - git config user.name 'Cirrus CI'
        - git commit -m "Regenerate site with $CIRRUS_CHANGE_IN_REPO\n\n$CIRRUS_CHANGE_MESSAGE\n[skip ci]"
        - git push -q "https://${GITHUB_PUSH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git" $CIRRUS_BRANCH

# vim: set expandtab shiftwidth=4 softtabstop=4:
